### ISSUE TITLE
Delete old resources before regenerating SDK

### ISSUE THREAD

**Issue by AntoineDao** [pollination/csharp-sdk#31]
When Models or entire APIs have their names changed or are deleted in the OpenAPI spec they are not removed from PollinationSDK package that is generated. This is problematic because it leads to code duplication.

I propose we run the following command before each generation script:

```console
rm -rf src/PollinationSDK && rm -rf src/PollinationSDK.Test
```

I have noticed that the csproj file and some helper modules have been added to these folders however so we might have to deal with them first.

Related to pollination/pollination-server#80

**Comment by MingboPeng** [comment]
fixed in #32
